import type { Metadata } from 'next'
import { Bricolage_Grotesque } from 'next/font/google'
import './globals.css'

const bricolage = Bricolage_Grotesque({
  subsets: ['latin'],
  axes: ['wdth', 'opsz'],
  variable: '--font-bricolage',
  display: 'swap',
})

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export const metadata: Metadata = {
  title: { default: 'Lively', template: '%s - Lively' },
  description: 'All you need',
  metadataBase: new URL(process.env.APP_URL ?? 'http://localhost:3000'),
}

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="en" className={`${bricolage.variable} h-full antialiased`}>
      <body className="bg-paper text-ink flex min-h-full flex-col">
        {children}
      </body>
    </html>
  )
}
